on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' # Only on PRs, see also build_and_deploy below
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS and build
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm install
          npm run build

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only on a push to the main branch (like when PR's are merged)
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS and build
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm install
          npm run build
          touch build/.nojekyll
      - name: 'Deploy website'
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build
          token: ${{ secrets.TOKEN }}
