on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' # Only on PRs, see also build_and_deploy below
    steps:
      - uses: actions/checkout@v2
      - name: "Setup NodeJS and build TailwindCSS"
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm install
          npm run build
      - name: "Build website"
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          BUILD_ONLY: true
          TOKEN: fake-secret

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only on a push to the main branch (like when PR's are merged)
    steps:
      - uses: actions/checkout@v2
      - name: "Setup NodeJS and build TailwindC"
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: |
          npm install
          npm run build
      - name: "Build and deploy website"
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          TOKEN: ${{ secrets.TOKEN }}